// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzaLpBD87bIVpirvXgVlMo8_vVK1og2GY',
    appId: '1:22214204005:web:3461c1839625900d49448c',
    messagingSenderId: '22214204005',
    projectId: 'ambulance-tracker-11812',
    authDomain: 'ambulance-tracker-11812.firebaseapp.com',
    storageBucket: 'ambulance-tracker-11812.appspot.com',
    measurementId: 'G-493TERVVGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDymF6MBSLLNTI-qlAF_0Gb4CBIIqfMmhw',
    appId: '1:22214204005:android:2956a635b7c74bd449448c',
    messagingSenderId: '22214204005',
    projectId: 'ambulance-tracker-11812',
    storageBucket: 'ambulance-tracker-11812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFp8_G1TRUFwm8kKXh4rM-K3qgD3FQk4o',
    appId: '1:22214204005:ios:6a53d9d29e11827849448c',
    messagingSenderId: '22214204005',
    projectId: 'ambulance-tracker-11812',
    storageBucket: 'ambulance-tracker-11812.appspot.com',
    iosBundleId: 'com.example.ambulanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFp8_G1TRUFwm8kKXh4rM-K3qgD3FQk4o',
    appId: '1:22214204005:ios:4651a082a958eb6549448c',
    messagingSenderId: '22214204005',
    projectId: 'ambulance-tracker-11812',
    storageBucket: 'ambulance-tracker-11812.appspot.com',
    iosBundleId: 'com.example.ambulanceTracker.RunnerTests',
  );
}
